using UnityEngine;

public class BarSceneBuilder : MonoBehaviour
{
    // This scene builder is intentionally disabled to avoid duplicate object creation with the cozy room layout.
    // The actual room structure is generated by the cozy room layout script.
    public bool buildOnStart = false;
    public bool isBuilt => true;

    public void BuildScene()
    {
        // Intentionally left empty.
    }

    private void Start()
    {
        // Intentionally left empty.
    }
}
